Added new feature to show sublime uptime helps you to know how long you working
Add: Control clock update interval from setting file
Add: setting to display clock only when there is a file in view
     or display always like before
Add: Show sublime uptime helps you to know how long you working
Fixed: AttributeError: 'NoneType' object has no attribute 'active_view'
Which was caused when there was no file in view